name: Test & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: ☑️ Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: 💎 Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.7

    - name: 🧪 Install gems
      run: |
        cd ./docs
        bundle config set path 'vendor/bundle'
        bundle install --jobs 4 --retry 3

    - name: 🔧 Build & Test
      run: |
        cd ./docs
        JEKYLL_ENV=production bundle exec jekyll build
        bundle exec rake upsert_data_by_readme
        bundle exec rake test

    - name: 🔔 Notify results
      env:
        IDOBATA_GITHUB_ACTIONS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
      if: always() && ( env.IDOBATA_GITHUB_ACTIONS!= null )
      uses: yasslab/idobata_notify@main
      with:
        idobata_hook_url: ${{ env.IDOBATA_GITHUB_ACTIONS }}

    - name: 🚀 Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        cd ./docs
        if [ -n "$(git status en ja --porcelain)" ]; then
          git config --global user.name  "Yohei Yasukawa"
          git config --global user.email "yohei@yasslab.jp"
          git checkout main
          git add en ja
          git commit -m '🤖 Generate page(s) by README'
          git push origin main
        fi

    - name: 🚨 Notify alert if failed on deployment
      env:
        IDOBATA_GITHUB_ACTIONS: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
      if: failure() && (env.IDOBATA_GITHUB_ACTIONS != null)
      uses: mahaker/actions-idobata@v1.1.2
      with:
        hookUrl: ${{ secrets.IDOBATA_GITHUB_ACTIONS }}
        format: 'markdown'
        message: |
          <span class='label label-danger'>本番環境</span> @yasulab :warning: デプロイに失敗したためロールバックされました: https://remotework.jp/ ([build](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}))
